
CREATE TABLE tb_user (
    usr_id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    usr_email    VARCHAR(255) NOT NULL,
    usr_password VARCHAR(255) NOT NULL,
    usr_type     VARCHAR(30) NOT NULL
);

CREATE TABLE tb_credit_brand (
    cbr_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    cbr_name VARCHAR(30) NOT NULL
);

CREATE TABLE tb_customer (
    cus_id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    cus_name       VARCHAR(255) NOT NULL,
    cus_cpf        CHAR(11) NOT NULL,
    cus_genre      CHAR(1) NOT NULL,
    cus_active     INTEGER NOT NULL,
    cus_phone_type VARCHAR(15) NOT NULL,
    cus_phone_ddd  CHAR(2) NOT NULL,
    cus_phone      VARCHAR(9) NOT NULL,
    cus_born_date  DATE NOT NULL,
    cus_user_id    INTEGER NOT NULL
);

CREATE TABLE tb_address (
    add_id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    add_cep          CHAR(9) NOT NULL,
    add_name         VARCHAR(255) NOT NULL,
    add_street       VARCHAR(255) NOT NULL,
    add_number       INTEGER NOT NULL,
    add_country      VARCHAR(100) NOT NULL,
    add_street_type  VARCHAR(50) NOT NULL,
    add_neighborhood VARCHAR(100) NOT NULL,
    add_observation  VARCHAR(255),
    add_default      INTEGER NOT NULL,
    add_city         VARCHAR(100) NOT NULL,
    add_state        VARCHAR(100) NOT NULL,
    add_customer_id  INTEGER NOT NULL
);

CREATE TABLE tb_credit_card (
    cre_id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    cre_number       CHAR(16) NOT NULL,
    cre_holder       VARCHAR(100) NOT NULL,
    cre_cvv          CHAR(3) NOT NULL,
    cre_default      INTEGER NOT NULL,
    cre_customer_id  INTEGER NOT NULL,
    cre_credit_brand INTEGER NOT NULL
);

CREATE TABLE tb_category (
    cat_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    cat_name VARCHAR(100) NOT NULL
);

CREATE TABLE tb_pricing_group (
    pgr_id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pgr_name          VARCHAR(30) NOT NULL,
    pgr_percent_value NUMERIC(5,2) NOT NULL
);

CREATE TABLE tb_chair (
    chr_id               INTEGER GENERATED BY DEFAULT AS IDENTITY,
    chr_name             VARCHAR(255) NOT NULL,
    chr_sell_price       NUMERIC(8,2) NOT NULL,
    chr_description      TEXT NOT NULL,
    chr_active           INTEGER NOT NULL DEFAULT 1,
    chr_height           NUMERIC(5,2) NOT NULL,
    chr_width            NUMERIC(5,2) NOT NULL,
    chr_length           NUMERIC(5,2) NOT NULL,
    chr_weight           NUMERIC(5,2) NOT NULL,
    chr_average_rating   NUMERIC(3,2) NOT NULL DEFAULT 0.00,
    chr_pricing_group_id INTEGER NOT NULL
);

CREATE TABLE tb_supplier (
    sup_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    sup_name VARCHAR(100) NOT NULL
);

CREATE TABLE tb_item (
    itm_id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    itm_entry_date  DATE NOT NULL DEFAULT CURRENT_DATE,
    itm_amount      INTEGER NOT NULL,
    itm_unit_cost   NUMERIC(8,2) NOT NULL,
    itm_reserved    INTEGER NOT NULL DEFAULT 0,
    itm_version     INTEGER NOT NULL DEFAULT 0,
    itm_chair_id    INTEGER NOT NULL,
    itm_supplier_id INTEGER NOT NULL
);

CREATE TABLE tb_cart (
    car_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    car_item_entry_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    car_item_limit          INTEGER NOT NULL,
    car_item_amount         INTEGER NOT NULL,
    car_item_price          NUMERIC(8,2) NOT NULL,
    car_item_status         VARCHAR(30) NOT NULL,
    car_customer_id         INTEGER NOT NULL,
    car_item_id             INTEGER NOT NULL
);

CREATE TABLE tb_order (
    ord_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ord_status              VARCHAR(30) NOT NULL,
    ord_created_date        DATE NOT NULL DEFAULT CURRENT_DATE,
    ord_updated_date        TIMESTAMP NOT NULL,
    ord_total_amount        INTEGER NOT NULL,
    ord_total_value         NUMERIC(12,2) NOT NULL,
    ord_customer_id         INTEGER NOT NULL,
    ord_billing_address_id  INTEGER NOT NULL,
    ord_delivery_address_id INTEGER NOT NULL
);

CREATE TABLE tb_coupon (
    cpn_id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    cpn_type        VARCHAR(30) NOT NULL,
    cpn_value       NUMERIC(5,2) NOT NULL,
    cpn_customer_id INTEGER NOT NULL
);

CREATE TABLE tb_chair_category (
    chc_id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    chc_chair_id    INTEGER NOT NULL,
    chc_category_id INTEGER NOT NULL
);

CREATE TABLE tb_chair_status_change (
    csc_id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    csc_reason     VARCHAR(255) NOT NULL,
    csc_status     VARCHAR(100) NOT NULL,
    csc_entry_date DATE NOT NULL DEFAULT CURRENT_DATE,
    csc_chair_id   INTEGER NOT NULL
);

CREATE TABLE tb_delivery (
    del_id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    del_status         VARCHAR(40) NOT NULL,
    del_amount         INTEGER NOT NULL,
    del_transporter    VARCHAR(50) NOT NULL,
    del_estimated_date DATE NOT NULL,
    del_order_id       INTEGER NOT NULL,
    del_item_id        INTEGER NOT NULL
);

CREATE TABLE tb_order_item (
    ori_id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ori_status      VARCHAR(50) NOT NULL,
    ori_amount      INTEGER NOT NULL,
    ori_sell_price  NUMERIC(8,2) NOT NULL,
    ori_freight_tax NUMERIC(5,2) NOT NULL,
    ori_item_id     INTEGER NOT NULL,
    ori_order_id    INTEGER NOT NULL
);

CREATE TABLE tb_order_coupon (
    ocp_id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ocp_paid_value NUMERIC(8,2) NOT NULL,
    ocp_coupon_id  INTEGER NOT NULL,
    ocp_order_id   INTEGER NOT NULL
);

CREATE TABLE tb_order_credit_card (
    occ_id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    occ_paid_value     NUMERIC(8,2) NOT NULL,
    occ_order_id       INTEGER NOT NULL,
    occ_credit_card_id INTEGER NOT NULL
);

CREATE TABLE tb_item_swap (
    its_id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    its_amount      INTEGER NOT NULL,
    its_status      VARCHAR(30) NOT NULL,
    its_total_value NUMERIC(8,2) NOT NULL,
    its_order_item_id     INTEGER NOT NULL
);

CREATE TABLE tb_price_change_request (
    pcr_id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pcr_requested_price NUMERIC(8,2) NOT NULL,
    pcr_status          VARCHAR(30) NOT NULL,
    pcr_chair_id        INTEGER NOT NULL
);

CREATE TABLE tb_insert_log (
    ilo_table    VARCHAR(20) NOT NULL,
    ilo_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ilo_user_id  INTEGER NOT NULL,
    ilo_row_id   INTEGER NOT NULL
);

CREATE TABLE tb_update_log (
    ulo_table     VARCHAR(20) NOT NULL,
    ulo_datetime  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ulo_column    VARCHAR(50) NOT NULL,
    ulo_row_id    INTEGER NOT NULL,
    ulo_old_value VARCHAR(255),
    ulo_new_value VARCHAR(255) NOT NULL,
    ulo_user_id   INTEGER NOT NULL
);

-- Comentários (mantidos em posição original)
COMMENT ON COLUMN tb_chair.chr_height IS 'Centimetros.';
COMMENT ON COLUMN tb_chair.chr_width IS 'Centimetros.';

-- Constraints (PKs e FKs) agrupadas no final
-- Chaves Primárias
ALTER TABLE tb_address ADD CONSTRAINT pk_tb_address PRIMARY KEY (add_id);
ALTER TABLE tb_cart ADD CONSTRAINT pk_tb_cart PRIMARY KEY (car_id);
ALTER TABLE tb_category ADD CONSTRAINT pk_tb_category PRIMARY KEY (cat_id);
ALTER TABLE tb_chair ADD CONSTRAINT pk_tb_chair PRIMARY KEY (chr_id);
ALTER TABLE tb_chair_category ADD CONSTRAINT pk_tb_chair_category PRIMARY KEY (chc_id);
ALTER TABLE tb_chair_status_change ADD CONSTRAINT pk_tb_chair_status_change PRIMARY KEY (csc_id);
ALTER TABLE tb_coupon ADD CONSTRAINT pk_tb_coupon PRIMARY KEY (cpn_id);
ALTER TABLE tb_credit_brand ADD CONSTRAINT pk_tb_credit_brand PRIMARY KEY (cbr_id);
ALTER TABLE tb_credit_card ADD CONSTRAINT pk_tb_credit_card PRIMARY KEY (cre_id);
ALTER TABLE tb_customer ADD CONSTRAINT pk_tb_customer PRIMARY KEY (cus_id);
ALTER TABLE tb_delivery ADD CONSTRAINT pk_tb_delivery PRIMARY KEY (del_id);
ALTER TABLE tb_item ADD CONSTRAINT pk_tb_item PRIMARY KEY (itm_id);
ALTER TABLE tb_item_swap ADD CONSTRAINT pk_tb_item_swap PRIMARY KEY (its_id);
ALTER TABLE tb_order ADD CONSTRAINT pk_tb_order PRIMARY KEY (ord_id);
ALTER TABLE tb_order_coupon ADD CONSTRAINT pk_tb_order_coupon PRIMARY KEY (ocp_id);
ALTER TABLE tb_order_credit_card ADD CONSTRAINT pk_tb_order_credit_card PRIMARY KEY (occ_id);
ALTER TABLE tb_order_item ADD CONSTRAINT pk_tb_order_item PRIMARY KEY (ori_id);
ALTER TABLE tb_price_change_request ADD CONSTRAINT pk_tb_price_change_request PRIMARY KEY (pcr_id);
ALTER TABLE tb_pricing_group ADD CONSTRAINT pk_tb_pricing_group PRIMARY KEY (pgr_id);
ALTER TABLE tb_supplier ADD CONSTRAINT pk_tb_supplier PRIMARY KEY (sup_id);
ALTER TABLE tb_user ADD CONSTRAINT pk_tb_user PRIMARY KEY (usr_id);

ALTER TABLE tb_order
    ADD CONSTRAINT fk_order_billing_address FOREIGN KEY (ord_billing_address_id) REFERENCES tb_address (add_id),
    ADD CONSTRAINT fk_order_delivery_address FOREIGN KEY (ord_delivery_address_id) REFERENCES tb_address (add_id);

ALTER TABLE tb_chair_category
    ADD CONSTRAINT fk_chair_category_category FOREIGN KEY (chc_category_id) REFERENCES tb_category (cat_id),
    ADD CONSTRAINT fk_chair_category_chair FOREIGN KEY (chc_chair_id) REFERENCES tb_chair (chr_id);

ALTER TABLE tb_chair_status_change
    ADD CONSTRAINT fk_chair_status_chair FOREIGN KEY (csc_chair_id) REFERENCES tb_chair (chr_id);

ALTER TABLE tb_item
    ADD CONSTRAINT fk_item_chair FOREIGN KEY (itm_chair_id) REFERENCES tb_chair (chr_id),
    ADD CONSTRAINT fk_item_supplier FOREIGN KEY (itm_supplier_id) REFERENCES tb_supplier (sup_id);

ALTER TABLE tb_price_change_request
    ADD CONSTRAINT fk_price_change_chair FOREIGN KEY (pcr_chair_id) REFERENCES tb_chair (chr_id);

ALTER TABLE tb_order_coupon
    ADD CONSTRAINT fk_order_coupon_coupon FOREIGN KEY (ocp_coupon_id) REFERENCES tb_coupon (cpn_id),
    ADD CONSTRAINT fk_order_coupon_order FOREIGN KEY (ocp_order_id) REFERENCES tb_order (ord_id);

ALTER TABLE tb_credit_card
    ADD CONSTRAINT fk_credit_card_brand FOREIGN KEY (cre_credit_brand) REFERENCES tb_credit_brand (cbr_id),
    ADD CONSTRAINT fk_credit_card_customer FOREIGN KEY (cre_customer_id) REFERENCES tb_customer (cus_id);

ALTER TABLE tb_order_credit_card
    ADD CONSTRAINT fk_order_credit_card_card FOREIGN KEY (occ_credit_card_id) REFERENCES tb_credit_card (cre_id),
    ADD CONSTRAINT fk_order_credit_card_order FOREIGN KEY (occ_order_id) REFERENCES tb_order (ord_id);

ALTER TABLE tb_address
    ADD CONSTRAINT fk_address_customer FOREIGN KEY (add_customer_id) REFERENCES tb_customer (cus_id);

ALTER TABLE tb_cart
    ADD CONSTRAINT fk_cart_customer FOREIGN KEY (car_customer_id) REFERENCES tb_customer (cus_id),
    ADD CONSTRAINT fk_cart_item FOREIGN KEY (car_item_id) REFERENCES tb_item (itm_id);

ALTER TABLE tb_coupon
    ADD CONSTRAINT fk_coupon_customer FOREIGN KEY (cpn_customer_id) REFERENCES tb_customer (cus_id);

ALTER TABLE tb_order
    ADD CONSTRAINT fk_order_customer FOREIGN KEY (ord_customer_id) REFERENCES tb_customer (cus_id);

ALTER TABLE tb_delivery
    ADD CONSTRAINT fk_delivery_item FOREIGN KEY (del_item_id) REFERENCES tb_item (itm_id),
    ADD CONSTRAINT fk_delivery_order FOREIGN KEY (del_order_id) REFERENCES tb_order (ord_id);

ALTER TABLE tb_item_swap
    ADD CONSTRAINT fk_item_swap_order_item FOREIGN KEY (its_order_item_id) REFERENCES tb_order_item (ori_id);

ALTER TABLE tb_order_item
    ADD CONSTRAINT fk_order_item_item FOREIGN KEY (ori_item_id) REFERENCES tb_item (itm_id),
    ADD CONSTRAINT fk_order_item_order FOREIGN KEY (ori_order_id) REFERENCES tb_order (ord_id);

ALTER TABLE tb_chair
    ADD CONSTRAINT fk_chair_pricing_group FOREIGN KEY (chr_pricing_group_id) REFERENCES tb_pricing_group (pgr_id);

ALTER TABLE tb_customer
    ADD CONSTRAINT fk_customer_user FOREIGN KEY (cus_user_id) REFERENCES tb_user (usr_id);

ALTER TABLE tb_customer ADD CONSTRAINT chk_customer_genre CHECK (cus_genre IN ('M', 'F'));
ALTER TABLE tb_customer ADD CONSTRAINT chk_customer_active CHECK (cus_active IN (0, 1));
ALTER TABLE tb_customer ADD CONSTRAINT chk_customer_born_date CHECK (cus_born_date > '1900-01-01');
ALTER TABLE tb_address ADD CONSTRAINT chk_address_number CHECK (add_number > 0);
ALTER TABLE tb_address ADD CONSTRAINT chk_address_default CHECK (add_default IN (0, 1));
ALTER TABLE tb_credit_card ADD CONSTRAINT chk_credit_card_default CHECK (cre_default IN (0, 1));
ALTER TABLE tb_pricing_group ADD CONSTRAINT chk_pricing_group_value CHECK (pgr_percent_value > 0);
ALTER TABLE tb_chair ADD CONSTRAINT chk_chair_sell_price CHECK (chr_sell_price > 0);
ALTER TABLE tb_chair ADD CONSTRAINT chk_chair_height CHECK (chr_height > 0);
ALTER TABLE tb_chair ADD CONSTRAINT chk_chair_width CHECK (chr_width > 0);
ALTER TABLE tb_chair ADD CONSTRAINT chk_chair_length CHECK (chr_length > 0);
ALTER TABLE tb_chair ADD CONSTRAINT chk_chair_weight CHECK (chr_weight > 0);
ALTER TABLE tb_chair ADD CONSTRAINT chk_chair_rating CHECK (chr_average_rating BETWEEN 0 AND 5);
ALTER TABLE tb_item ADD CONSTRAINT chk_item_amount CHECK (itm_amount >= 0);
ALTER TABLE tb_item ADD CONSTRAINT chk_item_unit_cost CHECK (itm_unit_cost > 0);
ALTER TABLE tb_item ADD CONSTRAINT chk_item_reserved CHECK (itm_reserved >= 0 AND itm_reserved <= itm_amount);
ALTER TABLE tb_cart ADD CONSTRAINT chk_cart_item_amount CHECK (car_item_amount > 0);
ALTER TABLE tb_cart ADD CONSTRAINT chk_cart_item_price CHECK (car_item_price > 0);
ALTER TABLE tb_order ADD CONSTRAINT chk_order_total_amount CHECK (ord_total_amount > 0);
ALTER TABLE tb_order ADD CONSTRAINT chk_order_total_value CHECK (ord_total_value > 0);
ALTER TABLE tb_coupon ADD CONSTRAINT chk_coupon_value CHECK (cpn_value > 0);
ALTER TABLE tb_delivery ADD CONSTRAINT chk_delivery_amount CHECK (del_amount > 0);
ALTER TABLE tb_order_item ADD CONSTRAINT chk_order_item_amount CHECK (ori_amount > 0);
ALTER TABLE tb_order_item ADD CONSTRAINT chk_order_item_price CHECK (ori_sell_price > 0);
ALTER TABLE tb_order_coupon ADD CONSTRAINT chk_order_coupon_value CHECK (ocp_paid_value > 0);
ALTER TABLE tb_order_credit_card ADD CONSTRAINT chk_order_credit_card_value CHECK (occ_paid_value > 0);
ALTER TABLE tb_item_swap ADD CONSTRAINT chk_item_swap_amount CHECK (its_amount > 0);
ALTER TABLE tb_item_swap ADD CONSTRAINT chk_item_swap_value CHECK (its_total_value > 0);
ALTER TABLE tb_price_change_request ADD CONSTRAINT chk_price_change_value CHECK (pcr_requested_price > 0);

INSERT INTO tb_credit_brand (cbr_id, cbr_name) VALUES (1, 'VISA');
INSERT INTO tb_credit_brand (cbr_id, cbr_name) VALUES (2, 'MASTERCARD');

INSERT INTO tb_pricing_group (pgr_name, pgr_percent_value) VALUES
('A', 1.00),
('B', 1.20),
('C', 1.50);

INSERT INTO tb_chair (chr_name, chr_sell_price, chr_description,
                     chr_height,   -- EM CENTÍMETROS (ex: 120 = 120cm = 1.20m)
                     chr_width,    -- EM CENTÍMETROS (ex: 60 = 60cm = 0.60m)
                     chr_length,   -- EM CENTÍMETROS (ex: 65 = 65cm = 0.65m)
                     chr_weight,   -- EM QUILOGRAMAS (ex: 15 = 15kg)
                     chr_average_rating, chr_pricing_group_id)
VALUES
-- Cadeira 1: Altura 120cm, Largura 60cm, Profundidade 65cm, Peso 15kg
('Cadeira Ergonômica Executiva', 299.99, 'Cadeira ergonômica com ajuste de altura e lombar',
 120, 60, 65, 15, 4.50, 2);
